dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.7.0
  shared_preferences: ^2.2.3
  in_app_review: ^2.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    # - assets/services/fuel.jpg
    # - assets/services/jump.jpg
    # - assets/services/battery.jpg
